### PR TITLE
Update OPENAI-README.md

### PR DESCRIPTION
**Pull request by MeDott29**

### CODE REVIEW

**Comment by Nirajparmar68** [comment]
Looks much better

**Review by Nirajparmar68 — COMMENTED** [review]
Looks nice!

**Comment by AdityaSkhorne** [comment]
Ok

**Comment by codemillmatt** [comment]
C# 9 introduced [target typed new](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/target-typed-new) - from what I'm gathering - that's not a popular feature 😄 

I'm going to close this out as the hack is over - but I am interested in any comments.

**Pull request closed without merging**
